package me.scolastico.runner.manager.dataholders;

public class RunnerConfiguration {

  private String tag = "latest";
  private String ghToken = "gh_token";
  private String group = "Default";
  private String org = "org";
  private String[] tags = new String[]{"ubuntu","autogenerated"};
  private int min = 2;
  private int max = 10;

  public String getGroup() {
    return group;
  }

  public void setGroup(String group) {
    this.group = group;
  }

  public String[] getTags() {
    return tags;
  }

  public void setTags(String[] tags) {
    this.tags = tags;
  }

  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public String getGhToken() {
    return ghToken;
  }

  public void setGhToken(String ghToken) {
    this.ghToken = ghToken;
  }

  public String getOrg() {
    return org;
  }

  public void setOrg(String org) {
    this.org = org;
  }

  public int getMin() {
    return min;
  }

  public void setMin(int min) {
    this.min = min;
  }

  public int getMax() {
    return max;
  }

  public void setMax(int max) {
    this.max = max;
  }

}
